import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Refund Policy — Super Warrior 30",
};

export default function RefundPolicyPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border/40 bg-background/90 backdrop-blur-md">
        <div className="container mx-auto flex h-16 items-center justify-between px-4 sm:px-6">
          <Link href="/" className="flex items-center space-x-2">
            <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground font-black text-xs">
              SW
            </span>
            <span className="text-base font-bold">Super Warrior 30</span>
          </Link>
          <Link href="/courses" className="text-xs font-semibold text-muted-foreground hover:text-foreground">
            Courses
          </Link>
        </div>
      </header>

      <main className="container mx-auto px-4 py-16 max-w-3xl space-y-6 text-xs text-muted-foreground leading-relaxed">
        <h1 className="text-2xl font-bold text-foreground">Refund Policy</h1>
        <p className="text-[11px] text-muted-foreground">Last updated: August 2026</p>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-foreground">1. Digital Course Access</h2>
          <p>
            Due to the immediate digital delivery and on-demand proprietary nature of our trading masterclasses, video lessons, and downloadable PDF companion guides, all course sales are generally considered final once content is accessed.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-foreground">2. Duplicate or Erroneous Charges</h2>
          <p>
            If you experienced an accidental duplicate billing transaction or payment gateway technical error, please notify our support team at support@superwarrior30.com with your order transaction details within 7 days. Verified duplicate charges will be refunded to the original payment method.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-foreground">3. Effect of Refund on Enrollment & Affiliate Commissions</h2>
          <p>
            Upon processing a refund or order cancellation, the associated course enrollment access is automatically revoked, and any referral commissions generated by that order are reversed.
          </p>
        </section>
      </main>

      <footer className="bg-card py-8 text-center text-xs text-muted-foreground border-t border-border/40">
        <p>© {new Date().getFullYear()} Super Warrior 30. All rights reserved.</p>
      </footer>
    </div>
  );
}
