import type { Metadata } from "next";
import Link from "next/link";
import { PublicNavbar } from "@/components/shared/public-navbar";

export const metadata: Metadata = {
  title: "Refund Policy — Rahul Trade Warrior Academy",
};

export default function RefundPolicyPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <PublicNavbar />

      <main className="container mx-auto px-4 py-16 max-w-3xl space-y-6 text-xs text-muted-foreground leading-relaxed">
        <h1 className="text-2xl font-bold text-foreground">Refund Policy</h1>
        <p className="text-[11px] text-muted-foreground">Last updated: August 2026</p>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-foreground">1. Digital Course Access</h2>
          <p>
            Due to the immediate digital delivery and on-demand proprietary nature of our trading masterclasses, video lessons, and downloadable PDF companion guides, all course sales are generally considered final once content is accessed.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-foreground">2. Duplicate or Erroneous Charges</h2>
          <p>
            If you experienced an accidental duplicate billing transaction or payment gateway technical error, please notify our support team at support@superwarrior30.com with your order transaction details within 7 days. Verified duplicate charges will be refunded to the original payment method.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-foreground">3. Effect of Refund on Enrollment & Affiliate Commissions</h2>
          <p>
            Upon processing a refund or order cancellation, the associated course enrollment access is automatically revoked, and any referral commissions generated by that order are reversed.
          </p>
        </section>
      </main>

      <footer className="bg-card py-8 text-center text-xs text-muted-foreground border-t border-border/40">
        <p>© {new Date().getFullYear()} Super Warrior 30. All rights reserved.</p>
      </footer>
    </div>
  );
}
